# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=30)),
                ('result_type', models.SmallIntegerField(choices=[(1, 'Numeric'), (2, 'Text')])),
                ('reference_text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', tinymce.models.HTMLField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtest.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResultMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alternate_name', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='resultmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtest.TestCategory'),
        ),
        migrations.AddField(
            model_name='resultmaster',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtest.Patient'),
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtest.ResultMaster'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugtest.TestCategory'),
        ),
    ]
