# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0002_auto_20160705_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Test Category', 'verbose_name_plural': 'Test Categories'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
