# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0003_auto_20160705_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reference_text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
