# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0004_auto_20160705_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('name',), 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AddField(
            model_name='analysis',
            name='profiles',
            field=models.ManyToManyField(to='drugtest.TestProfile'),
        ),
    ]
