# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0006_auto_20160705_0635'),
        ('drugtest', '0002_staff_username'),
    ]

    operations = [
    ]
