# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:32
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = 'initial_data'

def load_initial(apps, schema_editor):
<<<<<<< HEAD
    pass
    # call_command('loaddata', fixture, app_label='drugtest')
=======
    # call_command('loaddata', fixture, app_label='drugtest')
    pass
>>>>>>> 4f965beb18865e735f692da98fb36cf83ec3ea85

class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0007_merge'),
    ]

    operations = [
        migrations.RunPython(load_initial)
    ]
