# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0008_load_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('name',), 'verbose_name': 'Test'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result_type',
            field=models.SmallIntegerField(choices=[(1, 'Numeric'), (2, 'Text')], default=2),
        ),
    ]
