# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0009_auto_20160707_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmaster',
            name='category',
        ),
        migrations.AddField(
            model_name='resultmaster',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
