# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0010_auto_20160707_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmaster',
            name='physician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drugtest.Physician'),
            preserve_default=False,
        ),
    ]
