# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0011_resultmaster_physician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reference_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resultdetail',
            name='result',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
