# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0012_auto_20160725_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='components',
            field=models.CharField(blank=True, default='RESULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='reference_text',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
