# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugtest', '0015_auto_20160725_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmaster',
            name='medical_technologist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='MedTech', to='drugtest.Staff'),
        ),
        migrations.AlterField(
            model_name='resultmaster',
            name='pathologist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pathologist', to='drugtest.Staff'),
        ),
    ]
